use_frameworks!

platform :ios, '8.0'

target 'BasicTools_Example' do
  pod 'BasicTools', :path => '../'

  target 'BasicTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
